# Generated by Django 2.0.2 on 2018-04-18 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('run_time', models.DateTimeField()),
                ('output', models.TextField()),
                ('output_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='pipe',
            name='pipe_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.Pipeline'),
        ),
    ]
