# Generated by Django 2.0.2 on 2018-04-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipe',
            name='input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='output_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='run_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
