# Generated by Django 2.0.2 on 2018-05-21 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('host', models.URLField()),
                ('base_path', models.TextField()),
                ('title', models.TextField()),
                ('version', models.TextField()),
                ('openapi_version', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('example', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('enum', models.TextField(blank=True, null=True)),
                ('required', models.TextField()),
                ('default', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('maximum', models.TextField(blank=True, null=True)),
                ('minimum', models.TextField(blank=True, null=True)),
                ('nested', models.ManyToManyField(related_name='sub_param', to='browser.Parameter')),
            ],
        ),
        migrations.CreateModel(
            name='PathRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('DELETE', 'DELETE'), ('PUT', 'PUT'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('CONNECT', 'CONNECT')], max_length=10)),
                ('path', models.TextField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.ComponentSpecification')),
                ('parameters', models.ManyToManyField(to='browser.Parameter')),
            ],
        ),
        migrations.CreateModel(
            name='PathResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('description', models.TextField()),
                ('parameters', models.ManyToManyField(to='browser.Parameter')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.PathRequest')),
            ],
        ),
        migrations.AddField(
            model_name='pathrequest',
            name='responses',
            field=models.ManyToManyField(related_name='ResponseTo', to='browser.PathResponse'),
        ),
    ]
