# Generated by Django 2.0.2 on 2018-02-14 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('component_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.CharField(max_length=200)),
                ('request_description', models.CharField(max_length=200)),
                ('request_type', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('DELETE', 'DELETE'), ('PUT', 'PUT'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS'), ('CONNECT', 'CONNECT')], max_length=10)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.ComponentSpecification')),
            ],
        ),
    ]
