# Generated by Django 2.0.2 on 2018-02-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componentspecification',
            old_name='component_description',
            new_name='description',
        ),
    ]
